ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '${ALB_SSL_REDIRECT}'
    alb.ingress.kubernetes.io/group.name: ${ALB_GROUP_NAME}
    alb.ingress.kubernetes.io/healthcheck-path: ${ALB_HEALTHCHECK_PATH}
    alb.ingress.kubernetes.io/listen-ports: '${ALB_LISTENING_PORTS}'
    alb.ingress.kubernetes.io/scheme: ${ALB_SCHEME}
    alb.ingress.kubernetes.io/target-type: ${ALB_TARGET_TYPE}
    external-dns.alpha.kubernetes.io/hostname: ${ING_HOSTNAME}
  hosts:
    - host: ${ING_HOSTNAME}
      paths:
        - path: ${ING_PATH}
          pathType: ${ING_PATH_TYPE}