apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: dev
            url: https://kubernetes.default.svc
      - list:
          elements:
          - chart: uptime
            namespace: arvin
            releaseName: uptime-kuma
            revision: HEAD
          - chart: nginx
            namespace: arvin
            releaseName: nginx
            revision: HEAD
  template:
    metadata:
      name: '{{chart}}'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:arvin-pjr/argocd-test.git
        targetRevision: HEAD
        path: 'charts/{{chart}}'
        helm:
          releaseName: '{{releaseName}}'
          valueFiles:
          - 'values-{{cluster}}.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'